### ISSUE TITLE
Update for v2.3

### ISSUE THREAD

**Issue by tomsmalley** [tomsmalley/semantic-reflex#16]
v2.3 should work as is, but there are at least a couple of transitions which would be missing: `zoom` and `glow`
https://semantic-ui.com/introduction/new.html

**Comment by mulderr** [comment]
Heads up that v2.3 switched to FA 5. Some icons do look a bit different, lots are more bold. With same exact markup. In case anyone's wondering:
* Semantic reuses FA without modifications so not a Semantic issue
* FA declares v5 not backwards compatible so not an FA issue either
* Some best equivalents of v4 icons in v5 ended up in FA Pro (rather unfortunate)

Anyway... not a bug but manual tweaking may be necessary in some cases.

**Comment by tomsmalley** [comment]
Closed in #30
