### ISSUE TITLE
Tests fail consistently

### ISSUE THREAD

**Issue by 3noch** [tomsmalley/semantic-reflex#21]
I'm seeing consistent test failure but only on Mac. Are there ways we can make the tests more reliable?

**Comment by tomsmalley** [comment]
I've also seen this. (from what I remember) the tests rely on events returning from `delay` to have the same order as the input event, but this is not the case sometimes (mostly on mac it seems?). I think those tests were based on a poor assumption and should perhaps be removed.

**Comment by tomsmalley** [comment]
Closed by just commenting out bad tests in https://github.com/tomsmalley/semantic-reflex/commit/66731a0d04d795b811c7a247b4416c0d002a2b38
