### ISSUE TITLE
How to change the theme?

### ISSUE THREAD

**Issue by johnny555** [tomsmalley/semantic-reflex#22]
I'd like to be able to change the default theme. 
However, alot of the semantic-ui docs https://semantic-ui.com/usage/theming.html don't seem to make sense when I look at this repo. 
For example, where is the site.variables file?

**Comment by tomsmalley** [comment]
This library has no effect on theming: you’ll need to write your theme and compile with lessc as usual, just load your custom semantic.css file instead of the default one.

**Comment by johnny555** [comment]
Ok thanks!
