### ISSUE TITLE
Match the record style of upstream

### ISSUE THREAD

**Issue by tomsmalley** [tomsmalley/semantic-reflex#6]
Instead of `_buttonColor` we should probably have `_button_color`. Upstream would dictate `_buttonConfig_color` but I think that's too verbose.

**Comment by roberth** [comment]
The upstream convention does let you disambiguate between inputs and outputs easily and it'd be more consistent.

**Comment by tomsmalley** [comment]
True. I suspect I would regret `button_color` down the line, having thought about it. Consistency is important!

**Comment by tomsmalley** [comment]
Fixed as of 1df75c0751b0a429360982bda08ea7cf4f24071a
